EXTRAKEY_ENABLE = yes
OLED_ENABLE= yes
RGBLIGHT_ENABLE = yes
SEND_STRING_ENABLE= yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE= yes
WPM_ENABLE = yes
ENCODER_ENABLE = yes
#need space!!
LTO_ENABLE = yes
EXTRAFLAGS += -flto
AUDIO_ENABLE = no
AUTO_SHIFT_ENABLE= no
BACKLIGHT_ENABLE= no
BLUETOOTH_ENABLE= no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
MUSIC_ENABLE= no
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
SWAP_HANDS_ENABLE = no
 
SRC +=  ./lib/layer_state_reader.c
SRC +=  ./lib/keylogger.c
SRC +=  ./lib/timelogger.c

